[project]
name = "battleships"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.2.5",
    "pyfiglet>=1.0.2",
]
